# A workflow that runs all test with an emulator
name: Android CI

#Select when and on what [branch]
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Job uses macos, I found the ubuntu could stall starting the emulator.
jobs:
  test:
    runs-on: macos-latest
    steps:
        #Get the main branch
      - name: checkout
        uses: actions/checkout@v4
        # update java sdk to run with our project
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: enable gradle
        run: chmod +x gradlew

        #Start the emulator that will run the script for testing.
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.30.1
        with:
          #Set to our min api level
          api-level: 30
          # Default target will not work with api 30 need to specifiy google_apis, aosp_atd, google_atd
          target: google_apis # optional, default is default
          #The script that will run all the tests
          script: ./gradlew connectedDebugAndroidTest